export const SIGN_UP_ROUTE= "/grrg"
export const SIGN_IN_ROUTE= "/"
export const ACCOUNT_ROUTE = "/account/:id"
export const CHAT_ROOM_ROUTE = "/chats/:id"
export const GROUP_ROOM_ROUTE = "/chats/:id"